<?php

namespace Projects\SocialSportsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FootballTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FootballTeamRepository extends EntityRepository
{
}
